### ISSUE TITLE
[Report bug] Part of the email placeholder is hidden

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#71]
**Summary**
The modal says `Please make sure to give us a way to`.  
I tried resizing and hovering, but I was unable to see the full text.

**Expected behavior**
Bigger input field or different placeholder text.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63543088-42b18180-c522-11e9-938f-964c263f44ce.png)

**Comment by nico3333fr** [comment]
If this text is really important and **not already contained** in the `label`, I would suggest **not** to rely on `placeholder` attribute (we have this problem of hidden text, and also this is not accessible because not properly vocalized) and put it under/below the `input`.

Best accessible way to achieve it **is to link the field to its additional description** (wherever it is) via `aria-describedby="an_id"`:

```
<input aria-describedby="an_id" ...>
<span id="an_id">Please make sure to give us a way to.. blahblahblah</span>
```
The value of the `id` is not important, as long as it is the same used for `id` and `aria-describedby`.
